@include('templates.formulario.input', ['label' => 'CPF', 'input' => 'cpf', 'attributes' => ['placeholder' => 'CPF']])
@include('templates.formulario.input', ['label' => 'Nome','input' => 'Nome', 'attributes' => ['placeholder' => 'Nome']])
@include('templates.formulario.input', ['label' => 'Telefone','input' => 'Telefone', 'attributes' => ['placeholder' => 'Telefone']])
@include('templates.formulario.input', ['label' => 'E-mail','input' => 'E-mail', 'attributes' => ['placeholder' => 'E-mail']])
@include('templates.formulario.password', ['label' => 'Senha','input' => 'Senha', 'attributes' => ['placeholder' => 'Senha']])
